# Generated by Django 3.2.5 on 2022-05-09 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20220504_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireitem',
            name='order',
        ),
        migrations.AddField(
            model_name='questionnaireitem',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_items', to='questionnaire.questionnaire'),
            preserve_default=False,
        ),
    ]
