# Generated by Django 3.2.5 on 2022-05-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testquestionnaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionnaire',
            name='prepardedby',
            field=models.CharField(blank=True, default=1, max_length=150),
            preserve_default=False,
        ),
    ]
