# Generated by Django 3.2.5 on 2022-05-11 16:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testquestionnaire', '0002_alter_testquestionnaire_prepardedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testquestionnaire',
            name='prepardedby',
        ),
        migrations.AddField(
            model_name='testquestionnaire',
            name='RFS_Note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=' Copy and Paste RFS Info and any related RFS Notes here?', null=True),
        ),
    ]
