# Generated by Django 3.2.5 on 2022-03-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sizingtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sizingtypename', models.CharField(blank=True, db_column='Sizingtypename', max_length=150, null=True)),
                ('Sizingtypedesc', models.CharField(blank=True, db_column='Sizingtypedesc', max_length=150, null=True)),
                ('Sizingtypetype', models.CharField(blank=True, db_column='Sizingtype', max_length=150, null=True)),
                ('memo', models.CharField(blank=True, db_column='Memo', max_length=150, null=True)),
            ],
        ),
    ]
