# Generated by Django 3.2.5 on 2022-03-23 16:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sizingtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizingtype',
            name='memo',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
