# Generated by Django 3.2.5 on 2022-03-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220203_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='SpecialItemsDesc1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='SpecialItemsDesc2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='SpecialItemsDesc3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='SpecialItemsDesc4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='SpecialItemsDesc5',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent10_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent11_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent12_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent13_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent14_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent15_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent1_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent2_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent3_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent4_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent5_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent6_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent7_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent8_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
