# Generated by Django 3.2.5 on 2022-03-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220301_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='prodcomponent9_desc',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
