# Generated by Django 3.2.5 on 2022-03-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitem_srvshourscalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='nummonths',
            field=models.FloatField(default='12'),
        ),
    ]
