# Generated by Django 3.2.5 on 2022-03-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_orderitem_nummonths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='srvshourscalc',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
