# Generated by Django 3.2.5 on 2022-03-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_srvshourscalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='nummonths',
            field=models.IntegerField(default='12'),
        ),
    ]
