# Generated by Django 3.2.5 on 2022-03-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_orderitem_nummonths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='executetransitionplan_transitionhoursitem',
            field=models.FloatField(default='0.30'),
        ),
    ]
