# Generated by Django 3.2.5 on 2022-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20220315_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_line_mgr_hrs',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='second_line_mgr_hrs',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_transformation_hours',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='sum_transition_hours',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='transformation_hours',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='transition_hours',
            field=models.FloatField(default='0.0'),
        ),
    ]
