# Generated by Django 3.2.5 on 2022-03-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20220323_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_fte',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='transformation_fte',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AddField(
            model_name='order',
            name='transition_fte',
            field=models.FloatField(default='0.0'),
        ),
    ]
