# Generated by Django 3.2.5 on 2022-03-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20220323_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='RequesterEmail',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='RequesterFirstName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='RequesterLastName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='RequesterRole',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='Restricted_Delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Restricted_Delivery_Explanation',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='Revenue_Structure_Cost_Explain',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
