# Generated by Django 3.2.5 on 2022-03-24 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220323_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Revenue_Structure_Select',
            field=models.CharField(choices=[('Cost Recovery', 'Cost Recovery'), ('Revenue Share', 'Revenue Share'), ('Please Explain', 'Please Explain')], default='Select-One', max_length=20),
        ),
    ]
