# Generated by Django 3.2.5 on 2022-03-24 14:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_order_revenue_structure_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='AIX',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='AntiVirusMalware',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='BigFix_Patching_Scanning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Citrix',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='CustomerStatus',
            field=models.CharField(choices=[('Cost Recovery', 'Cost Recovery'), ('Revenue Share', 'Revenue Share'), ('Please Explain', 'Please Explain')], default='Select-One', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='DLP_on_Servers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='DLP_on_Workstations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Encryption_on_Servers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Encryption_on_Workstations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Environment_and_Platforms_Note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Firewall_on_Servers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Firewall_on_Workstations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Firm_Price_or_NBIE',
            field=models.CharField(choices=[('Firm', 'Firm'), ('NBIE', 'NBIE')], default='Select-One', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='HIPs_on_Servers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='HIPs_on_Workstations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Integrity_Monitoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Linux',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='NAS_Storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Other_Features_or_Platforms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Other_Features_or_Platforms_Note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Questionaire_num_consoles',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='Questionaire_num_ipaddress',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='Questionaire_num_server',
            field=models.IntegerField(db_column='Numserver', default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='Questionaire_num_total_endpoints',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='Questionaire_num_workstation',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='order',
            name='Service_Delivery_Requirements',
            field=models.CharField(choices=[('Asia/Pacific', 'Asia/Pacific'), ('Europe', 'Europe'), ('Latin America', 'latin America'), ('North America', 'North America'), ('None', 'None')], default='Select-One', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='Solution_Design',
            field=models.CharField(choices=[('Priyadarshi Achar - AP', 'Asia/Pacific'), ('David Lugg - Europe', 'David Lugg - Europe'), ('Julie Keane - Europe', 'Julie Keane - Europe'), ('Marek Wolsan - Europe', 'Marek Wolsan'), ('Steve Chew - Europe', 'Steve Chew'), ('Kiyomi Miura - Japan', 'Kiyomi Miura - Japan'), ('Marcello Belloni Gomes - LA', 'Marcello Belloni Gomes'), ('Greg Sinclair - MEA', 'Greg Sinclair - MEA'), ('David Cunningham - NA', 'David Cunningham - NA'), ('Page Farmer - NA', 'Page Farmer - NA'), ('Gerry Comeau - WW', 'Gerry Comeau - WW'), ('Jonathan Planko - WW', 'Jonathan Planko - WW'), ('None', 'None')], default='Select-One', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='URL_Filtering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='VDI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='Windows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='prodcomponent1_wkstn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='Revenue_Structure_Select',
            field=models.CharField(choices=[('Cost Recovery', 'Cost Recovery'), ('Revenue Share', 'Revenue Share')], default='Select-One', max_length=150),
        ),
    ]
